### ISSUE TITLE
SA1642 does not handle structs.

### ISSUE THREAD

**Issue by jcasale** [DotNetAnalyzers/StyleCopAnalyzers#1686]
When a struct has ctor, the inspection forces the usage of "class" instead of "struct".

**Comment by sharwell** [comment]
This should have been fixed as part of #418. What version are you using?

**Comment by jcasale** [comment]
Hi,
I am using 1.0.0-beta014 from Nuget. Sorry, I forgot to check for closed issues as well, however it seems to still exist for me.

Thanks.

**Comment by sharwell** [comment]
Can you provide sample code which reproduces the issue? The tests include multiple checks for the proper use of `struct` in the summary text, so it looks like the problem is in something we hadn't thought of yet.

Thanks!

**Comment by jcasale** [comment]
Sam,
After creating a sample from my project, I realized the problem was on my end.
Sorry for the noise and I really appreciate the help.

Thanks.

**Comment by sharwell** [comment]
No problem, glad to hear it's working for you now :smile:
