### ISSUE TITLE
SA1000 doesn't handle 'target-typed' new

### ISSUE THREAD

**Issue by davkean** [DotNetAnalyzers/StyleCopAnalyzers#3214]
With C# 9.0, SA1000 complains about "target type new expressions":

```
private readonly object syncObject = new();
```

## Expected: 
No message:

## Actual:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	SA1000	The keyword 'new' should be followed by a space.	Microsoft.VisualStudio.ProjectSystem	C:\CPS\src\Microsoft.VisualStudio.ProjectSystem\Build\Logging\ProjectBuildTargetErrorList.cs	21	Active

```

**Comment by sharwell** [comment]
This was fixed by #3187

**Comment by bstoinev** [comment]
I know this is an old issue that is supposed to be fixed but I can still see the exactly described message when using target-typed new()

I'm using VS2022 with StyleCop.Analyzers 1.1.18 NuGet package.

**Comment by sharwell** [comment]
We try to always assign milestones to fixed issues so it's easy to compare versions. This one was released in 1.2.0-beta.261.
