### ISSUE TITLE
Invalid fix all result for SA1101 (PrefixLocalCallsWithThis)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#466]
When the batch fixer applies the code fix for SA1101 to the following block, the result is not correct.

#### Original code:

```csharp
string fixedTest = @"namespace Namespace
{
    class Type
    {
        void Foo()
        {
            int x = 1 " + Sign + @" " + Sign + @"3;
        }
    }
}
";
```

#### Expected result

```csharp
string fixedTest = @"namespace Namespace
{
    class Type
    {
        void Foo()
        {
            int x = 1 " + this.Sign + @" " + this.Sign + @"3;
        }
    }
}
";
```

#### Actual result:

```csharp
string fixedTest = @"namespace Namespace
{
    class Type
    {
        void Foo()
        {
            int x = 1 " + this.Sign + @" " + Sign + @" " + this.Sign + @"3;
        }
    }
}
";
```

**Comment by sharwell** [comment]
@pdelvo How would you suggest we handle this? It looks like a case where the batch fixer should not have a problem, yet it does.

**Comment by pdelvo** [comment]
It seems like it has problems if the diagnostic can appear in one like. I start to not really trust the batch fixer any more. I think we should implement a batch fixer for this. 
Maybe we could implement a generic, more robust batch fixer we can utilize if the built in batch fixer does a poor job

**Comment by mavasani** [comment]
@sharwell @pdelvo #320 has been fixed and I have added a unit test for your fixer scenario. Please verify if it fixes your code fix provider's FixAll.

**Comment by sharwell** [comment]
@mavasani I just ran this code again in Visual Studio 2015 CTP 6, and found that the bug still occurred. Was the issue supposed to be corrected in CTP 6, or is it part of a later release?

To reproduce, clone this repository and open the file **NumberSignSpacingTestBase.cs**. Do a Replace All in the file to replace `this.` with the empty string. A warning will appear (from the analyzer which is installed in the project) requesting each of these instances be changed back to `this.`. If you use the Fix All provider to correct all instances in the document, you'll find the document is restored to the state in which you cloned it, with the exception of the specific expression which I reported in dotnet/roslyn#320.

**Comment by AArnott** [comment]
Has anyone opened a bug with the Roslyn team?

**Comment by sharwell** [comment]
@AArnott I did previously (dotnet/roslyn#320), but it was closed as fixed. I left a comment there tonight regarding the ongoing reports of errors related to this.

**Comment by pdelvo** [comment]
Can this issue be closed?
